name: gym-atari-play
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pip:
      - gymnasium>=0.27,<1.0
      - gymnasium[atari,accept-rom-license]
      - ale-py
      - pygame
      - autorom[accept-rom-license]
